# Generated by Django 3.2.3 on 2025-06-15 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialrecord',
            options={'verbose_name': 'Запись ДДС', 'verbose_name_plural': 'Записи ДДС'},
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='created_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата создания записи'),
        ),
    ]
